version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "node-fetch"
      - dependency-name: "chalk"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
